<?php
return [
    'en' => [
        'CLIENT_FANTASY' => 'Fantasy Name',
        'CLIENT_NAME' => 'Client Full Name',
        'CLIENT_ADDRESS' => 'Address',
        'ACTION' => 'Action',
        'ADD' => 'Add',
        'EDIT' => 'Edit',
        'DELETE' => 'Delete',
        'APP_LANGUAGE' => 'Application Language is set to ',
        'CLIENT_ADMIN' => 'Client Administration',
        'ADD_CLIENT' => 'Add Client',
        'EDIT_CLIENT' =>'Edit Client',
        'UPDATE' => 'Update',
        'SAVE' => 'Save',
        'PAGE_TITLE' => 'ZLOGISTIK CLIENTS',
        'SELECT_LANGUAGE' => 'Select Language',
        'CLIENT_CREATED' => 'Client created',
        'CLIENT_UPDATED' => 'Client updated',
        'CLIENT_DELETED' => 'Client deleted',
    ],
    'es' => [
        'CLIENT_FANTASY' => 'Nombre Fantasia',
        'CLIENT_NAME' => 'Razón Social',
        'CLIENT_ADDRESS' => 'Dirección',
        'ACTION' => 'Nombre Fantasia',
        'ADD' => 'Agregar',
        'EDIT' => 'Editar',
        'DELETE' => 'Eliminar',
        'APP_LANGUAGE' => 'El lenguaje de la aplicación está en ',
        'CLIENT_ADMIN' => 'Administración de clientes',
        'ADD_CLIENT' => 'Agregar Cliente',
        'EDIT_CLIENT' =>'Editar Cliente',
        'UPDATE' => 'Actualizar',
        'SAVE' => 'Guardar',
        'PAGE_TITLE' => 'CLIENTES ZLOGISTIK',
        'SELECT_LANGUAGE' => 'Seleccionar Idioma',        'CLIENT_CREATED' => 'Se ha creado el cliente',
        'CLIENT_UPDATED' => 'Se ha actualizado el cliente',
        'CLIENT_DELETED' => 'Se ha eliminado el cliente',

    ]
];
